# Generated by Django 3.0.8 on 2020-07-25 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('job_type', models.CharField(choices=[('full time ', 'Full Time'), ('part time ', 'Part Time ')], max_length=25)),
            ],
        ),
    ]
